SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP FUNCTION INSERTA_REPRESENTANTE_PRELIMINAR(ID_ESTADO_IN  DECIMAL(2,0) , 
ID_DISTRITO_IN DECIMAL(2,0), ASOCIACION_IN DECIMAL(1,0),PARTIDO_CANDIDATO_IN DECIMAL(6,0), 
TIPO_REPRESENTANTE_IN CHAR(1), SECCION_IN DECIMAL(4,0), CASILLA_IN CHAR(6), 
CALIDAD_REPRESENTANTE_IN CHAR(1) , CLAVE_ELECTOR_IN CHAR(11 ), NOMBRE_IN VARCHAR(35), 
APELLIDO_PATERNO_IN VARCHAR(35), APELLIDO_MATERNO_IN VARCHAR(35), SEXO_IN CHAR(1), 
DOMICILIO_IN VARCHAR(200));
**/
CREATE OR REPLACE FUNCTION INSERTA_RESPONSABLES_ACREDITACION (ID_ESTADO_IN  DECIMAL(2,0) , 
ASOCIACION_IN DECIMAL(1,0),PARTIDO_CANDIDATO_IN DECIMAL(6,0), NOMBRE_IN VARCHAR(35), 
APELLIDO_PATERNO_IN VARCHAR(35), APELLIDO_MATERNO_IN VARCHAR(35) ) 
  RETURNS VOID AS $$
    DECLARE
      VAR_FECHA_HORA TIMESTAMP := NOW();
      VAR_USUARIO VARCHAR(50) := CURRENT_USER;
    BEGIN
    IF NOT EXISTS(SELECT * FROM RESPONSABLES_ACREDITACION WHERE NOMBRE = NOMBRE_IN AND
     APELLIDO_PATERNO = APELLIDO_PATERNO_IN AND APELLIDO_MATERNO = APELLIDO_MATERNO_IN )
      THEN
           IF ( IS_CADENA(NOMBRE_IN) AND IS_CADENA(APELLIDO_PATERNO_IN) 
              AND IS_CADENA(APELLIDO_MATERNO_IN)  )
            THEN
              INSERT INTO  RESPONSABLES_ACREDITACION VALUES (1,ID_ESTADO_IN, 
                ASOCIACION_IN , PARTIDO_CANDIDATO_IN, NOMBRE_IN, APELLIDO_PATERNO_IN, 
                APELLIDO_MATERNO_IN, VAR_USUARIO , VAR_FECHA_HORA );
            ELSE
              RAISE EXCEPTION 'UPS! SE GENERO UN ERROR AL VALIDAR ALGUNA DE LAS SIGUIENTES CADENAS. -> %'
               ,  $4 || ' '|| $5 || ' '||$6
              USING HINT = 'REVISA QUE TU CADENA SEA UNA CADENA VALIDA';
              RETURN  ;
    END IF;
    ELSE 
    RAISE EXCEPTION 'NOMBRE DEL RESPONSABLE DE ACREDITACION YA SE ENCUENTRA REGISTRADO ::: %' 
    , $4 || ' '|| $5 || '  '||$6
    USING HINT = 'REVISA QUE TU NOMBRE DEL REPRESENTANTE NO SE ENCUeNTRE YA REGISTRADO EN LA BASE';
    RETURN  ;
   END IF ;
      END;
    $$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION INSERTA_responsables_acreditacion (ID_ESTADO_IN  DECIMAL(2,0) , 
ASOCIACION_IN DECIMAL(1,0),PARTIDO_CANDIDATO_IN DECIMAL(6,0), NOMBRE_IN VARCHAR(35), 
APELLIDO_PATERNO_IN VARCHAR(35), APELLIDO_MATERNO_IN VARCHAR(35) ) 
 IS 'Procedimiento para insertar a un responsable de acreditacion de representantes de partidos politicos.';