SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP FUNCTION ASISTENCIAS_REPRESENTANTES( ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0) , ID_ESTADO_IN  DECIMAL(2,0) , ID_DISTRITO_FEDERAL_IN NUMERIC(2,0) , 
      SECCION_IN NUMERIC(5,0) ,   TIPO_CASILLA_IN VARCHAR(6)  , TIPO_PRESENCIA_IN VARCHAR(1)  , TIPO_FIRMA_IN VARCHAR(1) );
**/
CREATE OR REPLACE FUNCTION ASISTENCIAS_REPRESENTANTES( ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0) , ID_ESTADO_IN  DECIMAL(2,0) , ID_DISTRITO_FEDERAL_IN NUMERIC(2,0) , 
	SECCION_IN NUMERIC(5,0) ,   TIPO_CASILLA_IN VARCHAR(6) , TIPO_PRESENCIA_IN VARCHAR(1) , TIPO_FIRMA_IN VARCHAR(1) ) RETURNS VOID AS $$
    	DECLARE
			VAR_FECHA_HORA TIMESTAMP := NOW();
			VAR_USUARIO VARCHAR(50) := CURRENT_USER;
			VAR_CALIDAD_REPRESENTANTE VARCHAR(1);
			VAR_ID_REPRE_PRE INTEGER;
     BEGIN
	IF  EXISTS(SELECT * FROM representantes_acreditados JOIN REPRESENTANTES_CASILLA USING (ID_REPRESENTANTE_PRE)  WHERE ID_ESTADO = ID_ESTADO_IN AND ID_DISTRITO_FEDERAL = ID_DISTRITO_FEDERAL_IN 
	AND SECCION = SECCION_IN  AND  TIPO_CASILLA  =  TIPO_CASILLA_IN  AND  ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN )
     THEN 
      IF NOT EXISTS (SELECT * FROM ASISTENCIAS  WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN)
        THEN 
          IF TIPO_PRESENCIA_IN = 'I'
           THEN 
              INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , TIPO_FIRMA_IN , NULL , NULL , TIPO_PRESENCIA_IN , 
                NULL , NULL ,VAR_USUARIO  , VAR_FECHA_HORA );
           ELSEIF  TIPO_PRESENCIA_IN = 'F'
            THEN 
              INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , NULL , TIPO_FIRMA_IN , NULL , NULL , 
                TIPO_PRESENCIA_IN , NULL ,VAR_USUARIO  , VAR_FECHA_HORA );
           ELSEIF  TIPO_PRESENCIA_IN = 'C'
            THEN 
              INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , NULL , NULL , TIPO_FIRMA_IN , NULL , 
                NULL , TIPO_PRESENCIA_IN ,VAR_USUARIO  , VAR_FECHA_HORA );
           ELSE 
		RAISE EXCEPTION 'UPS! SE GENERO UN ERROR NO EXISTE EL TIPO DE ASISTENCIA QUE DESEAS REGISTRAR. -> %' , $6
                USING HINT = 'REVISA QUE TU ASISTENCIA SEA VALIDA.';
                RETURN  ;
            END IF;
        ELSE 
           IF TIPO_PRESENCIA_IN = 'I'
            THEN 
              UPDATE  ASISTENCIAS  SET FIRMA_INICIO  = TIPO_FIRMA_IN , PRESENCIA_INICIO =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;
	   ELSEIF  TIPO_PRESENCIA_IN = 'F'
            THEN 
              UPDATE  ASISTENCIAS  SET FIRMA_FIN  = TIPO_FIRMA_IN , PRESENCIA_FIN =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;
           ELSEIF  TIPO_PRESENCIA_IN = 'C'
            THEN    
              UPDATE  ASISTENCIAS  SET FIRMA_COMPUTO  = TIPO_FIRMA_IN , PRESENCIA_COMPUTO =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;
           ELSE 
		RAISE EXCEPTION 'UPS! SE GENERO UN ERROR NO EXISTE EL TIPO DE ASISTENCIA QUE DESEAS REGISTRAR. -> %' , $6
                USING HINT = 'REVISA QUE TU ASISTENCIA SEA VALIDA.';
                RETURN  ;
            END IF;
          END IF ;
        ELSE

        IF EXISTS(SELECT * FROM CASILLAS  WHERE ID_ESTADO = ID_ESTADO_IN AND ID_DISTRITO_FEDERAL = ID_DISTRITO_FEDERAL_IN  AND SECCION = SECCION_IN  AND  
              TIPO_CASILLA  =  TIPO_CASILLA_IN  AND  APROBACION_CASILLA_CONSEJO = 'S' )
        THEN 
           IF  EXISTS(SELECT * FROM representantes_acreditados JOIN REPRESENTANTES_GENERALES USING (ID_REPRESENTANTE_PRE)  WHERE   ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN )
             THEN 
                     IF NOT EXISTS (SELECT * FROM ASISTENCIAS  WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN)
			THEN 
			    IF TIPO_PRESENCIA_IN = 'I'
				THEN 
				     INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , TIPO_FIRMA_IN , NULL , NULL , TIPO_PRESENCIA_IN , 
				      NULL , NULL ,VAR_USUARIO  , VAR_FECHA_HORA );
		     ELSEIF  TIPO_PRESENCIA_IN = 'F'
			THEN 
				INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , NULL , TIPO_FIRMA_IN , NULL , NULL , 
				TIPO_PRESENCIA_IN , NULL ,VAR_USUARIO  , VAR_FECHA_HORA );
		      ELSEIF  TIPO_PRESENCIA_IN = 'C'
			THEN 
				INSERT INTO ASISTENCIAS VALUES (ID_REPRESENTANTE_ACRE_IN , ID_ESTADO_IN , ID_DISTRITO_FEDERAL_IN ,SECCION_IN , TIPO_CASILLA_IN , NULL , NULL , TIPO_FIRMA_IN , NULL , 
				NULL , TIPO_PRESENCIA_IN ,VAR_USUARIO  , VAR_FECHA_HORA );
			ELSE 
				RAISE EXCEPTION 'UPS! SE GENERO UN ERROR NO EXISTE EL TIPO DE ASISTENCIA QUE DESEAS REGISTRAR. -> %' , $6
				USING HINT = 'REVISA QUE TU ASISTENCIA SEA VALIDA.';
				RETURN  ;
				END IF;
			ELSE 
			  IF TIPO_PRESENCIA_IN = 'I'
				THEN 
					UPDATE  ASISTENCIAS  SET FIRMA_INICIO  = TIPO_FIRMA_IN , PRESENCIA_INICIO =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;	
		          ELSEIF   TIPO_PRESENCIA_IN = 'F'
		         	 THEN 
					UPDATE  ASISTENCIAS  SET FIRMA_FIN  = TIPO_FIRMA_IN , PRESENCIA_FIN =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;
			  ELSEIF   TIPO_PRESENCIA_IN = 'C'
				THEN 
					UPDATE  ASISTENCIAS  SET FIRMA_COMPUTO  = TIPO_FIRMA_IN , PRESENCIA_COMPUTO =  TIPO_PRESENCIA_IN   WHERE ID_REPRESENTANTE_ACRE = ID_REPRESENTANTE_ACRE_IN ;
				ELSE 
					RAISE EXCEPTION 'UPS! SE GENERO UN ERROR NO EXISTE EL TIPO DE ASISTENCIA QUE DESEAS REGISTRAR. -> %' , $6
					USING HINT = 'REVISA QUE TU ASISTENCIA SEA VALIDA.';
					RETURN  ;
			END IF;
		END IF ;
               ELSE 
		  RAISE EXCEPTION 'UPS! SE GENERO UN ERROR AL INTENTAR HACER EL  REGISTRO '  
                  USING HINT = 'REVISA QUE TUS DATOS SEAN VALIDOS.';
                  RETURN  ;
		END IF;
		ELSE 
		  RAISE EXCEPTION 'UPS! SE GENERO UN ERROR LA CASILLA EN LA QUE DESEAS REGISTRAR UNA ASISTENCIA NO SE ACUNETRA APROBADA POR EL CONSEJO O NO EXISTE. -> %' ,  $2 || ' ' ||$3 || ' ' || $4 || ' ' || $5
                  USING HINT = 'REVISA LOS DATOS DE TU CASILLA SEAN VALIDOS.';
                  RETURN  ;
		END IF;
	      END IF;
	END;
    $$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION ASISTENCIAS_REPRESENTANTES ( ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0) , ID_ESTADO_IN  DECIMAL(2,0) , ID_DISTRITO_FEDERAL_IN NUMERIC(2,0) , 
      SECCION_IN NUMERIC(5,0) ,   TIPO_CASILLA_IN VARCHAR(6) , TIPO_PRESENCIA_IN VARCHAR(1) , TIPO_FIRMA_IN VARCHAR(1) )  
IS 'Procedimiento para agregar asistencias a los represetantes .';