SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
 /**
DROP FUNCTION INSERTA_SUSTITUCION_REPRESENTANTE(ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0), 
  ID_REPRESENTANTE_PRELIMINAR NUMERIC(10,0) , ID_RESPONSABLE_ACREDITACION NUMERIC(10,0) , ACREDITADO CHARACTER(1));
**/
CREATE OR REPLACE FUNCTION INSERTA_SUSTITUCION_REPRESENTANTE(ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0), 
 ID_REPRESENTANTE_PRELIMINAR NUMERIC(10,0) , ID_RESPONSABLE_ACREDITACION NUMERIC(10,0) , ACREDITADO CHARACTER(1))
  RETURNS VOID AS $$
    DECLARE
      VAR_FECHA_HORA TIMESTAMP := NOW();
      VAR_USUARIO VARCHAR(50) := CURRENT_USER;
      VAR_ID_REPRE_ACRE NUMERIC(10,0);
     BEGIN
      IF (CUMPLE_CONDICION_SUSTITUCION (ID_REPRESENTANTE_ACRE_IN , ID_REPRESENTANTE_PRELIMINAR ) )
        THEN
          UPDATE REPRESENTANTES_ACREDITADOS SET ACTIVO = 'F' WHERE ID_REPRESENTANTE_ACRE = $1 ;
          VAR_ID_REPRE_ACRE := (SELECT * FROM INSERTA_ACREDITACION_REPRESENTANTE (ID_RESPONSABLE_ACREDITACION  , ID_REPRESENTANTE_PRELIMINAR ) );
             RAISE NOTICE    '::DESPUES DEL INSERTA_ACREDITACION_REPRESENTANTE :: ->   %' , VAR_ID_REPRE_ACRE ; 
          VAR_ID_REPRE_ACRE := (SELECT ID_REPRESENTANTE_ACRE FROM REPRESENTANTES_ACREDITADOS WHERE 
                                  ID_REPRESENTANTE_PRE =  ID_REPRESENTANTE_PRELIMINAR );       
                  RAISE  NOTICE '::VAR_ID_REPRE_ACRE :: -> %' , VAR_ID_REPRE_ACRE   ;         
          INSERT INTO REPRESENTANTES_SUSTITUCION VALUES ( 1 ,ID_REPRESENTANTE_ACRE_IN , VAR_ID_REPRE_ACRE , ACREDITADO , 
                            TO_CHAR(VAR_FECHA_HORA, 'HH12:MI:SS')   , VAR_USUARIO , VAR_FECHA_HORA );
        ELSE
          RAISE EXCEPTION 'UPS! NO LA SUSTITUCION QUE DESEAS REALIZAR NO ES VALIDA.' 
      USING HINT = 'REVISA QUE TUS REPRESENTANTES SEAN COMPATIBLES.';
      RETURN  ;
      END IF;
     END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION INSERTA_SUSTITUCION_REPRESENTANTE (ID_REPRESENTANTE_ACRE_IN NUMERIC(10,0), 
  ID_REPRESENTANTE_PRELIMINAR NUMERIC(10,0) , ID_RESPONSABLE_ACREDITACION NUMERIC(10,0)  , ACREDITADO CHARACTER(1)  )  IS 
	'Procedieminto almacenado encargado de hacer las sustituciones de representantes acreditados por representantes 
    que aun son preliminares.';
