SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP  FUNCTION GENERA_ID_REPRE_DATO() ;
**/
CREATE OR REPLACE FUNCTION GENERA_ID_REPRE_DATO() 
RETURNS INTEGER  AS $$
DECLARE
	ID_REPRE_DATO INTEGER;
    BEGIN
	 ID_REPRE_DATO := (SELECT CASE WHEN MAX(ID_REPRESENTANTE_DATOS) IS NOT NULL 
	 	THEN MAX(ID_REPRESENTANTE_DATOS) +1	 ELSE COUNT(ID_REPRESENTANTE_DATOS) + 1 
	 	END ID_NUEVO FROM REPRESENTANTES.REPRESENTANTES_DATOS ); 
	RETURN ID_REPRE_DATO;
	END;
    $$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION GENERA_ID_REPRE_DATO(   )  IS
	'Función encargada de Regresar el valor del identificador único de la tabla  representantes_datos.'; 