SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP  FUNCTION GENERA_ID_REPRE_PRE(  ) ;
**/
CREATE OR REPLACE FUNCTION GENERA_ID_REPRE_PRE(  ) 
RETURNS INTEGER  AS $$
DECLARE
	ID_REPRE_DATO INTEGER;
    BEGIN
	 ID_REPRE_DATO := (SELECT CASE WHEN MAX(ID_REPRESENTANTE_PRE) IS NOT NULL
	 	THEN MAX(ID_REPRESENTANTE_PRE) +1 ELSE COUNT(ID_REPRESENTANTE_PRE) +1 
	 	END ID_NUEVO  FROM REPRESENTANTES.REPRESENTANTES_PRELIMINARES ); 
	RETURN ID_REPRE_DATO;
	END;
    $$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION GENERA_ID_REPRE_PRE(   )  IS
	'Función encargada de regresar el valor del identificador único de la tabla representante_pre.'; 