SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) );
**/
CREATE OR REPLACE FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) ) 
RETURNS INTEGER  AS $$
DECLARE
	ID_REPRE_DATO INTEGER;
    BEGIN
	 ID_REPRE_DATO := (SELECT ID_REPRESENTANTE_DATOS FROM REPRESENTANTES.REPRESENTANTES_DATOS WHERE CLAVE_ELECTOR = CLAVE_ELECTOR_IN ); 
	IF ID_REPRE_DATO IS NOT NULL THEN 
	RETURN ID_REPRE_DATO;
	ELSE 
	RAISE EXCEPTION 'UPS! SE GENERO UN ERROR AL YA QUE NO SE ECUENTRA LA CLAVE DE ELECTOR. -> %' , $1 
	USING HINT = 'REVISA QUE LA CLAVE DE ELECTOR SI EXISTA.';
	END IF;
	END;
    $$ LANGUAGE PLPGSQL;
    
COMMENT ON FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) )  IS
	'Función encargada de regresar el valor del id del representantes que ya existe en la tabla.';