SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) );
**/
CREATE OR REPLACE FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) ) 
RETURNS INTEGER  AS $$
DECLARE
	ID_REPRE_DATO INTEGER;
    BEGIN
	 ID_REPRE_DATO := (SELECT ID_REPRESENTANTE_DATOS FROM REPRESENTANTES.REPRESENTANTES_DATOS WHERE CLAVE_ELECTOR = CLAVE_ELECTOR_IN ); 
	IF ID_REPRE_DATO IS NOT NULL THEN 
	RETURN ID_REPRE_DATO;
	ELSE 
	RAISE EXCEPTION 'Ups! se genero un error al ya que no se ecuentra la clave de elector. -> %' , $1 
	USING HINT = 'Revisa que la clave de elector si exista.';
	END IF;
	END;
    $$ LANGUAGE PLPGSQL;
    
COMMENT ON FUNCTION REGRESA_ID_REPRE_DATO( CLAVE_ELECTOR_IN CHAR(11) )  IS
	'Función encargada de regresar el valor del id del representantes que ya existe en la tabla.';