SET SEARCH_PATH TO REPRESENTANTES , CASILLAS , GEOGRAFICO , PARTIDOSPOLITICOS;
/**
DROP FUNCTION IS_REPRESENTANTES_GENERALES_DISTRITO( INTEGER , INTEGER );
**/
CREATE OR REPLACE FUNCTION REPRESENTANTES_GENERALES_DISTRITO(INTEGER, INTEGER) 
RETURNS BOOLEAN  AS $$
DECLARE
	CANTIDA_REPRE_GENERAL INTEGER;
    BEGIN
	 CANTIDA_REPRE_GENERAL := (SELECT COUNT(*) FROM REPRESENTANTES_ACREDITADOS 
	 	JOIN  REPRESENTANTES_GENERALES USING (ID_REPRESENTANTE_PRE) WHERE 
	 	ID_ESTADO = $1 	AND ID_DISTRITO_FEDERAL = $2 AND ACTIVO = 'T'); 
	IF CANTIDA_REPRE_GENERAL < 8 THEN
		RETURN TRUE;
	ELSE
		RAISE EXCEPTION 'NO PUEDEN EXISTIR MAS DE 8 REPRESENTANTES GENERALES POR ID_DISTRITO.';
		RETURN FALSE;
	END IF;
	END;
    $$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION REPRESENTANTES_GENERALES_DISTRITO( INTEGER , INTEGER )  IS
	'Función encargada de validar que no existan mas de 8 representantes generales por estado y distrito .';